apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v6ey0x8bz-python 
  janus-idp.io/tekton: v6ey0x8bz-python
  backstage.io/kubernetes-id: v6ey0x8bz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v6ey0x8bz-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml