apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: v6ey0x8bz-python-gitops
  description: This is GitOps manifest for v6ey0x8bz-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=v6ey0x8bz-python
    backstage.io/kubernetes-id: v6ey0x8bz-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: v6ey0x8bz-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:v6ey0x8bz-python
